export enum todoOptions {
  TODO_OPTION_ALL = "TODO_OPTION_ALL",
  TODO_OPTION_COMPLETED = "TODO_OPTION_COMPLETED",
  TODO_OPTION_ACTIVE = "TODO_OPTION_ACTIVE",
}

export const TODO_LIST_ITEM_COUNT = "--todo-list-item-count";
